runtime: python37
instance_class: F4_HIGHMEM

env_variables:
  GCP_PROJECT: "finalprojectfansipan2019"
  GCS_BUCKET: "finalprojectfansipan2019"
  FIREBASE_CONFIG: "firebase_config.json"

handlers:
  - url: /static
    static_dir: static
  
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
